# dev
spring:
  config:
    activate:
      on-profile: "dev-h2"

  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  jpa:
    show-sql: true
    database: h2

    hibernate:
      ddl-auto: create-drop
